# Generated by Django 6.0.2 on 2026-03-06 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Describe your restaurant, cuisine style, and ambiance",
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("american", "American"),
                            ("asian", "Asian"),
                            ("italian", "Italian"),
                            ("mexican", "Mexican"),
                            ("indian", "Indian"),
                            ("french", "French"),
                            ("japanese", "Japanese"),
                            ("chinese", "Chinese"),
                            ("thai", "Thai"),
                            ("mediterranean", "Mediterranean"),
                            ("fusion", "Fusion"),
                            ("vegetarian", "Vegetarian"),
                            ("vegan", "Vegan"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "price_range",
                    models.CharField(
                        choices=[
                            ("$", "Budget-Friendly ($)"),
                            ("$$", "Moderate ($$)"),
                            ("$$$", "Upscale ($$$)"),
                            ("$$$$", "Fine Dining ($$$$)"),
                        ],
                        default="$$",
                        max_length=10,
                    ),
                ),
                (
                    "hours_open",
                    models.TimeField(default="09:00", help_text="Opening time"),
                ),
                (
                    "hours_close",
                    models.TimeField(default="21:00", help_text="Closing time"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Profile is visible to customers"
                    ),
                ),
                (
                    "is_temporarily_unavailable",
                    models.BooleanField(
                        default=False, help_text="Temporarily mark as unavailable"
                    ),
                ),
                (
                    "unavailable_reason",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("unavailable_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="restaurant_photos/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Set as main photo for the restaurant"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="nomz.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
    ]
