# Generated by Django 6.0.2 on 2026-03-06 23:44 (patched)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0002_restaurant_restaurantphoto"),
        ("nomz", "0002_loginlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataIngestionRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dataset", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed")], default="running", max_length=20)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_matched", models.IntegerField(default=0)),
                ("records_skipped", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantSourceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.CharField(choices=[("EATERIES", "Directory of Eateries"), ("DINING_OUT", "Dining Out NYC Locations"), ("DOHMH", "DOHMH Restaurant Inspection Results")], max_length=20)),
                ("external_id", models.CharField(max_length=200)),
                ("external_name", models.CharField(max_length=255)),
                ("external_address", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("confidence", models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ("source_url", models.URLField(blank=True, max_length=500, null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sources", to="nomz.restaurant")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["source", "external_id"], name="nomz_source_ext_1"),
                    models.Index(fields=["restaurant", "source"], name="nomz_source_rest_2"),
                ],
                "unique_together": {("source", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="InspectionRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("inspection_date", models.DateField()),
                ("inspection_key", models.CharField(max_length=200)),
                ("grade", models.CharField(blank=True, max_length=12, null=True)),
                ("score", models.IntegerField(blank=True, null=True)),
                ("critical_violations", models.IntegerField(default=0)),
                ("noncritical_violations", models.IntegerField(default=0)),
                ("violation_count", models.IntegerField(default=0)),
                ("inspection_type", models.CharField(blank=True, max_length=128, null=True)),
                ("action", models.CharField(blank=True, max_length=255, null=True)),
                ("violations", models.JSONField(blank=True, default=list)),
                ("camis", models.CharField(blank=True, max_length=80, null=True)),
                ("boro", models.CharField(blank=True, max_length=80, null=True)),
                ("raw_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("restaurant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inspections", to="nomz.restaurant")),
            ],
            options={
                "ordering": ["-inspection_date"],
                "indexes": [
                    models.Index(fields=["restaurant", "inspection_date"], name="nomz_insp_rest_1"),
                    models.Index(fields=["grade"], name="nomz_insp_grade_1"),
                ],
                "unique_together": {("restaurant", "inspection_key")},
            },
        ),
        migrations.AddField(
            model_name="restaurant",
            name="neighborhood",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisine",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="name_normalized",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="building",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="borough",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="zip_code",
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cuisine_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="composite_score",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="grade_latest",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="grade_score_latest",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="last_inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="composite_score_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["name_normalized", "zip_code"], name="nomz_restau_name_no_1bc4bb_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["borough", "zip_code"], name="nomz_restau_borough_8e6a1a_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["is_active"], name="nomz_restau_is_acti_f59dd9_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["latitude", "longitude"], name="nomz_restau_latitud_09565a_idx"),
        ),
    ]
