# Generated by Django 6.0.2 on 2026-03-08 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0002_restaurant_alter_userprofile_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiningOutLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "license_status",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("license_issue_date", models.DateField(blank=True, null=True)),
                ("license_expiration_date", models.DateField(blank=True, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("indoor", "Indoor"),
                            ("outdoor", "Outdoor"),
                            ("sidewalk", "Sidewalk"),
                            ("mixed", "Mixed"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "building_number",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "council_district",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "community_board",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("nta2020", models.CharField(blank=True, max_length=32, null=True)),
                ("boro_code", models.CharField(blank=True, max_length=20, null=True)),
                ("bin", models.CharField(blank=True, max_length=40, null=True)),
                ("bbl", models.CharField(blank=True, max_length=40, null=True)),
                ("capacity_estimate", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dining_out_profile",
                        to="nomz.restaurant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["restaurant"], name="nomz_dining_restaur_c37a72_idx"
                    ),
                    models.Index(
                        fields=["license_type", "license_status"],
                        name="nomz_dining_license_bddd53_idx",
                    ),
                ],
            },
        ),
    ]
