# Generated by Django 4.2.28 on 2026-03-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomz', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
