# Generated by Django 6.0.2 on 2026-03-09 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomz', '0004_alter_restaurant_owner'),
        ('nomz', '0004_merge_20260308_2129'),
    ]

    operations = [
    ]
