# Generated by Django 6.0.2 on 2026-03-21 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0008_userpreference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HEALTH_CHECK_FAILURE", "Health check failure"),
                            ("HIGH_ERROR_RATE", "High error rate"),
                            ("HIGH_LATENCY", "High latency"),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="HIGH",
                        max_length=16,
                    ),
                ),
                ("message", models.CharField(max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "request_path",
                    models.CharField(blank=True, max_length=2048, null=True),
                ),
                ("http_method", models.CharField(blank=True, max_length=10, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="system_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemPerformanceMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("method", models.CharField(db_index=True, max_length=10)),
                ("path", models.CharField(db_index=True, max_length=2048)),
                ("duration_ms", models.PositiveIntegerField()),
                ("status_code", models.PositiveIntegerField(db_index=True)),
                ("is_error", models.BooleanField(db_index=True, default=False)),
                (
                    "exception_class",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "exception_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at", "is_error"], name="nomz_sysperf_err_idx"
                    ),
                    models.Index(
                        fields=["created_at", "duration_ms"],
                        name="nomz_sysperf_lat_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemPerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interval_start", models.DateTimeField(db_index=True)),
                ("interval_end", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_requests", models.IntegerField()),
                ("error_requests", models.IntegerField()),
                ("error_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "avg_latency_ms",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_latency_ms",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
            options={
                "ordering": ["-interval_end"],
                "unique_together": {("interval_start", "interval_end")},
            },
        ),
    ]
