# Generated by Django 6.0.3 on 2026-03-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0010_loginlog_is_user_suspicious"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this business account has been approved by an administrator.",
            ),
        ),
    ]
