# Generated by Django 6.0.2 on 2026-03-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0009_restaurantownershipclaim"),
        ("nomz", "0010_loginlog_is_user_suspicious"),
    ]

    operations = []
