# Generated by Django 6.0.3 on 2026-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0011_userprofile_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_rejected",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this business account has been rejected by an administrator.",
            ),
        ),
    ]
