# Generated by Django 4.2.28 on 2026-03-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0013_review_moderationreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationreport",
            name="reason",
            field=models.CharField(
                choices=[
                    ("SPAM", "Spam or misleading"),
                    ("FRAUD", "Fraudulent activity"),
                    ("HARASSMENT", "Harassment or hate speech"),
                    ("INAPPROPRIATE", "Inappropriate content"),
                    ("OTHER", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
