# Generated by Django 4.2.28 on 2026-03-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0014_alter_moderationreport_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="is_flagged",
            field=models.BooleanField(
                default=False, help_text="Publicly flagged for fraudulent activity"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_flagged",
            field=models.BooleanField(
                default=False, help_text="Publicly flagged for fraudulent activity"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Profile is visible to users"
            ),
        ),
    ]
