# Generated by Django 6.0.2 on 2026-03-28 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0016_merge_20260326_0016"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ambience_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Ambience rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="cleanliness_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Cleanliness rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="dietary_accommodation_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Dietary accommodation quality rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="food_quality_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Food quality rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="location_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Location and accessibility rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="service_quality_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Service quality rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="value_rating",
            field=models.PositiveSmallIntegerField(
                default=4,
                help_text="Price-to-value rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Overall rating from 1 to 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
