# Generated by Django 4.2.28 on 2026-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0018_conversation_message"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="conversation",
            new_name="nomz_conver_restaur_1c14db_idx",
            old_name="nomz_conver_restaur_2307e8_idx",
        ),
        migrations.RenameIndex(
            model_name="conversation",
            new_name="nomz_conver_diner_i_dd8f4f_idx",
            old_name="nomz_conver_diner_i_8e69de_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="nomz_messag_convers_d418d4_idx",
            old_name="nomz_messag_convers_fbc997_idx",
        ),
        migrations.RenameIndex(
            model_name="message",
            new_name="nomz_messag_sender__212813_idx",
            old_name="nomz_messag_sender__9b55f5_idx",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="messaging_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Allow diners to send messages to this restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="response_hours_end",
            field=models.TimeField(
                blank=True,
                help_text="Latest time the restaurant responds to messages",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="response_hours_start",
            field=models.TimeField(
                blank=True,
                help_text="Earliest time the restaurant responds to messages",
                null=True,
            ),
        ),
    ]
