# Generated by Django 4.2.28 on 2026-03-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0019_add_restaurant_communication_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
