# Generated by Django 5.2.12 on 2026-04-07 17:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0022_messagenotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecalculatedRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "cuisine_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "price_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "dietary_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "neighborhood_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quality_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "historical_satisfaction_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "accuracy_feedback",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Great Match - User Loved It"),
                            (0, "Okay Match - User Indifferent"),
                            (-1, "Poor Match - User Disliked It"),
                        ],
                        help_text="Manual or inferred feedback on recommendation quality",
                        null=True,
                    ),
                ),
                (
                    "user_interacted",
                    models.BooleanField(
                        default=False,
                        help_text="Did user click/view this recommended restaurant?",
                    ),
                ),
                (
                    "days_to_interaction",
                    models.IntegerField(
                        blank=True,
                        help_text="Days until user interacted with this restaurant",
                        null=True,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of interaction (view, review, reservation, etc)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "recommendation_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Position in recommendation list at time of generation",
                        null=True,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interaction_detected_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Recalculated Recommendation",
                "verbose_name_plural": "Recalculated Recommendations",
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationModelMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_date", models.DateField(auto_now_add=True)),
                ("total_recommendations_given", models.IntegerField(default=0)),
                ("total_users_with_recommendations", models.IntegerField(default=0)),
                (
                    "successful_recommendations",
                    models.IntegerField(
                        default=0,
                        help_text="Number of recommendations that led to user interaction",
                    ),
                ),
                (
                    "avg_recommendation_accuracy",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage (0-100) of recommendations leading to interaction",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "avg_days_to_interaction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average days between recommendation and user interaction",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "cuisine_match_success_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "price_match_success_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "dietary_match_success_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "neighborhood_match_success_rate",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "avg_recommendation_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("recommendations_with_perfect_score", models.IntegerField(default=0)),
                (
                    "recommendations_updated_from_learning",
                    models.IntegerField(
                        default=0,
                        help_text="How many recommendation weights were adjusted based on learning",
                    ),
                ),
                (
                    "users_with_improved_weights",
                    models.IntegerField(
                        default=0,
                        help_text="Number of users whose preference weights improved accuracy",
                    ),
                ),
                ("last_recalculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recommendation Model Metric",
                "verbose_name_plural": "Recommendation Model Metrics",
                "ordering": ["-metric_date"],
            },
        ),
        migrations.CreateModel(
            name="UserInteractionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Restaurant View"),
                            ("profile_view", "Profile Page View"),
                            ("search", "Search Query"),
                            ("review_submitted", "Review Submitted"),
                            ("rating_given", "Rating Provided"),
                            ("recommendation_viewed", "Recommendation Viewed"),
                            ("recommendation_clicked", "Recommendation Clicked"),
                            ("reservation", "Reservation Made"),
                            ("menu_viewed", "Menu Viewed"),
                            ("photo_viewed", "Photos Viewed"),
                            ("contact_clicked", "Contact Info Clicked"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "search_query",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "satisfaction_score",
                    models.IntegerField(
                        blank=True,
                        help_text="User satisfaction: -1=bad, 0=neutral, 1-5=rating scale",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("time_spent_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "was_shared",
                    models.BooleanField(
                        default=False, help_text="Did user share this restaurant?"
                    ),
                ),
                (
                    "was_saved",
                    models.BooleanField(
                        default=False,
                        help_text="Did user save/favorite this restaurant?",
                    ),
                ),
                (
                    "was_recommended",
                    models.BooleanField(
                        default=False,
                        help_text="Was this a recommended restaurant shown to user?",
                    ),
                ),
                (
                    "recommendation_rank",
                    models.IntegerField(
                        blank=True,
                        help_text="Position in recommendation list (1=first, 2=second, etc)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Interaction History",
                "verbose_name_plural": "User Interaction Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="userpreference",
            name="composite_score_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Weight multiplier for restaurant quality score",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="cuisine_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Weight multiplier for cuisine matching (0.5-2.0, adjusted by learning)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="dietary_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Weight multiplier for dietary restrictions matching",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="historical_satisfaction_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0.5,
                help_text="Weight for historical user satisfaction with similar restaurants",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="last_recommendation_improvement_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time preference weights were improved by learning algorithm",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="last_recommendation_recalculated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time recommendations were calculated for this user",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="last_weights_adjustment_reason",
            field=models.CharField(
                blank=True,
                help_text="Reason why weights were last adjusted (for debugging)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="learning_data_quality_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Confidence in learned weights (0-100%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="minimum_interactions_for_learning",
            field=models.IntegerField(
                default=3,
                help_text="Minimum number of interactions needed before weight adjustment",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="neighborhood_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Weight multiplier for neighborhood preference",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="price_weight",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Weight multiplier for price range matching",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(2.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="recommendation_model_version",
            field=models.IntegerField(
                default=1,
                help_text="Which version of recommendation model is being used for this user",
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="successful_recommendations",
            field=models.IntegerField(
                default=0, help_text="Number of recommendations user interacted with"
            ),
        ),
        migrations.AddField(
            model_name="userpreference",
            name="total_recommendations_received",
            field=models.IntegerField(
                default=0, help_text="Total recommendations shown to this user"
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["user", "-last_recommendation_recalculated_at"],
                name="nomz_userpr_user_id_187c18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userpreference",
            index=models.Index(
                fields=["recommendation_model_version"],
                name="nomz_userpr_recomme_28344d_idx",
            ),
        ),
        migrations.AddField(
            model_name="recalculatedrecommendation",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculated_for_users",
                to="nomz.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="recalculatedrecommendation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calculated_recommendations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationmodelmetric",
            index=models.Index(fields=["-metric_date"], name="metric_date_idx"),
        ),
        migrations.AddField(
            model_name="userinteractionhistory",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_interactions",
                to="nomz.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="userinteractionhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interaction_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="recalculatedrecommendation",
            index=models.Index(fields=["user", "-calculated_at"], name="rec_user_date"),
        ),
        migrations.AddIndex(
            model_name="recalculatedrecommendation",
            index=models.Index(
                fields=["user_interacted", "-calculated_at"], name="rec_interacted_date"
            ),
        ),
        migrations.AddIndex(
            model_name="recalculatedrecommendation",
            index=models.Index(
                fields=["accuracy_feedback", "-created_at"], name="rec_accuracy_date"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteractionhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="userinteract_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteractionhistory",
            index=models.Index(
                fields=["restaurant", "-created_at"], name="userinteract_rest_date"
            ),
        ),
        migrations.AddIndex(
            model_name="userinteractionhistory",
            index=models.Index(
                fields=["user", "restaurant", "-created_at"],
                name="userinteract_user_rest_date",
            ),
        ),
        migrations.AddIndex(
            model_name="userinteractionhistory",
            index=models.Index(
                fields=["interaction_type", "-created_at"],
                name="userinteract_type_date",
            ),
        ),
    ]
