# Generated by Django 5.2.12 on 2026-04-07 18:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0023_recalculatedrecommendation_recommendationmodelmetric_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinteractionhistory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
