# Generated by Django 6.0.2 on 2026-04-11 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0024_alter_userinteractionhistory_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompositeScoreHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("algorithm_version", models.CharField(default="v2", max_length=32)),
                (
                    "trigger_source",
                    models.CharField(
                        choices=[
                            ("signal_review", "Review Saved Signal"),
                            ("signal_review_delete", "Review Deleted Signal"),
                            ("signal_inspection", "Inspection Saved Signal"),
                            ("signal_inspection_delete", "Inspection Deleted Signal"),
                            ("admin_action", "Django Admin Action"),
                            ("admin_dashboard", "Admin Dashboard"),
                            ("management_command", "Management Command"),
                            ("ingestion", "Ingestion Pipeline"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=32,
                    ),
                ),
                (
                    "trigger_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "composite_score",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "previous_composite_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "delta_from_previous",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, default="", max_length=12)),
                ("grade_score", models.IntegerField(default=0)),
                ("last_inspection_date", models.DateField(blank=True, null=True)),
                (
                    "inspection_component_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "review_component_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "price_value_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "operational_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("review_count", models.IntegerField(default=0)),
                (
                    "review_confidence",
                    models.DecimalField(decimal_places=3, default=0, max_digits=4),
                ),
                ("score_breakdown", models.JSONField(blank=True, default=list)),
                ("score_inputs", models.JSONField(blank=True, default=dict)),
                ("anomaly_flags", models.JSONField(blank=True, default=list)),
                ("is_anomalous", models.BooleanField(db_index=True, default=False)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_history",
                        to="nomz.restaurant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="composite_score_recalculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at"],
            },
        ),
        migrations.CreateModel(
            name="CompositeScoreAnomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("large_delta", "Large Score Delta"),
                            (
                                "low_confidence_high_score",
                                "Low Confidence With High Score",
                            ),
                            (
                                "stale_inspection_high_score",
                                "Stale Inspection With High Score",
                            ),
                        ],
                        db_index=True,
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_score_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_anomalies",
                        to="nomz.restaurant",
                    ),
                ),
                (
                    "score_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomalies",
                        to="nomz.compositescorehistory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="compositescorehistory",
            index=models.Index(
                fields=["restaurant", "-calculated_at"],
                name="nomz_compos_restaur_3d20b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compositescorehistory",
            index=models.Index(
                fields=["trigger_source", "-calculated_at"],
                name="nomz_compos_trigger_15233c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compositescorehistory",
            index=models.Index(
                fields=["is_anomalous", "-calculated_at"],
                name="nomz_compos_is_anom_d8bcf5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compositescoreanomaly",
            index=models.Index(
                fields=["restaurant", "is_resolved"],
                name="nomz_compos_restaur_b29a2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compositescoreanomaly",
            index=models.Index(
                fields=["anomaly_type", "severity", "is_resolved"],
                name="nomz_compos_anomaly_d9cc86_idx",
            ),
        ),
    ]
