# Generated by Django 4.2.28 on 2026-04-12 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nomz", "0026_friendconversation_friendmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendmessage",
            name="restaurant_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nomz.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="friendmessage",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FriendSharedRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_restaurants",
                        to="nomz.friendconversation",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nomz.restaurant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("conversation", "restaurant")},
            },
        ),
    ]
