# Generated by Django 4.2.28 on 2026-04-12 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nomz", "0027_friendmessage_restaurant_recommendation_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendconversation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="friendconversation",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="friendconversation",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="friendconversation",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="friend_chats", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="friendconversation",
            name="user1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_conversations_initiated_legacy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="friendconversation",
            name="user2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_conversations_received_legacy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
