# Generated by Django 4.2.28 on 2026-04-12 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nomz", "0028_alter_friendconversation_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendconversation",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_group_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
