# Generated by Django 4.2.28 on 2026-04-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0029_friendconversation_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="hours_close",
            field=models.TimeField(
                blank=True, default="21:00", help_text="Closing time", null=True
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="hours_open",
            field=models.TimeField(
                blank=True, default="09:00", help_text="Opening time", null=True
            ),
        ),
    ]
