# Generated by Django 6.0.2 on 2026-04-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0030_alter_restaurant_hours_close_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this business account has been approved by an administrator.",
            ),
        ),
    ]
